package com.orthodox.calendar.engine

import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * Runs the matcher over the bundled 2026 calendars and checks it against
 * `bio_assignments_2026.tsv`, generated by the reference implementation
 * (`scripts/shared/simulate_bio_matching.py` in the iOS repo, which iOS
 * `BioMatcher.swift` is also checked against).
 *
 * A wrong bio is worse than none, so a drift between the three implementations
 * shows up here as a concrete day and feast rather than as a rendering nobody
 * notices. Regenerate the fixture when the matcher rules or the bundled data
 * change — never edit it to make a failure go away.
 */
class BioMatcherTest {

    @Serializable private data class TFeast(val name: String, val moveable: Boolean = false)
    @Serializable private data class TBio(val title: String)
    @Serializable private data class TDay(
        val feasts: List<TFeast> = emptyList(),
        val saintBios: List<TBio>? = null
    )
    @Serializable private data class TFile(val days: Map<String, TDay>)

    private val json = Json { ignoreUnknownKeys = true }

    private fun assets(): File {
        for (path in listOf("src/main/assets/localization", "app/src/main/assets/localization")) {
            val dir = File(path)
            if (dir.isDirectory) return dir
        }
        throw IllegalStateException("bundled calendars not found from ${File(".").absolutePath}")
    }

    @Test
    fun `matches the reference assignments for every bundled locale`() {
        val fixture = javaClass.getResourceAsStream("/bio_assignments_2026.tsv")
            ?: error("bio_assignments_2026.tsv missing from test resources")
        val expected = fixture.bufferedReader().readLines()
            .filter { it.isNotBlank() && !it.startsWith("#") }
            .map { it.split("\t") }

        val files = HashMap<String, TFile>()
        var checked = 0
        for (row in expected) {
            val (locale, day, pairs) = row
            val file = files.getOrPut(locale) {
                json.decodeFromString(File(assets(), "calendar_${locale}_2026.json").readText())
            }
            val d = file.days[day] ?: error("$locale has no day $day")
            val bios = d.saintBios.orEmpty()
            val actual = BioMatcher.assign(
                feastNames = d.feasts.map { it.name },
                moveable = d.feasts.map { it.moveable },
                bioTitles = bios.map { it.title }
            )
            // A day can carry bios and still match nothing: a wrong bio is worse
            // than none, so an empty row is a result, not a gap in the fixture.
            val want = pairs.split(",").filter { it.isNotBlank() }.associate { p ->
                val (f, b) = p.split("=")
                f.toInt() to b.toInt()
            }
            // Name the feast and the bio, so a drift reads as "this saint got
            // that life" rather than as two integers.
            assertEquals(
                "$locale $day: " + want.keys.union(actual.keys).sorted().joinToString("; ") { i ->
                    val e = want[i]?.let { bios[it].title } ?: "—"
                    val a = actual[i]?.let { bios[it].title } ?: "—"
                    if (e == a) "" else "${d.feasts[i].name} expected [$e] got [$a]"
                }.trim(),
                want, actual
            )
            checked += want.size
        }
        assertTrue("fixture looks empty ($checked assignments)", checked > 5000)
    }

    @Test
    fun `a bio titled exactly like a feast goes to that feast, not to a tying neighbour`() {
        // 02-01 in the English calendar: four Macarii, and the greedy pass alone
        // would hand each bio to whichever tying feast came first.
        val feasts = listOf(
            "Venerable Macarius the Great of Egypt (390)",
            "Venerable Macarius the Roman of Novgorod (1550)",
            "Venerable Macarius of the Kiev Caves (12th c.)"
        )
        val bios = listOf(
            "Venerable Macarius of the Kiev Caves (12th c.)",
            "Venerable Macarius the Great of Egypt (390)"
        )
        val result = BioMatcher.assign(feasts, List(feasts.size) { false }, bios)
        assertEquals(mapOf(0 to 1, 2 to 0), result)
    }

    @Test
    fun `words are compared past inflection and typos but not across names`() {
        assertEquals(3, BioMatcher.tokenMatch("петар", "петар"))
        assertEquals(2, BioMatcher.tokenMatch("петар", "петра"))     // inflection
        assertEquals(2, BioMatcher.tokenMatch("тедот", "теодот"))    // dropped letter
        assertEquals(0, BioMatcher.tokenMatch("матија", "марија"))   // different names
    }

    @Test
    fun `two-letter words count only when capitalised`() {
        assertEquals(listOf("ор", "ii"), BioMatcher.tokens("Ор II"))
        assertEquals(emptyList<String>(), BioMatcher.tokens("св 1918"))
    }
}
